import { IConcert } from "@/types/IConcert";

export const concertList: IConcert[] = [
  {
    id: 202411,
    title: "W. A. Mozrt의 레퀴엠 KV626",
    date: "2024년 11월 14일 목요일 오후7시30분",
    place: "연세대학교 백주년기념관 콘서트홀",
    img_url: "/202411/01.jpg",
    performers: {
      conductor: "김혜옥",
      soloists: {
        소프라노: "최혜경",
        카운터테너: "장정권",
        테너: "김효종",
        베이스: "안대현",
      },
      choir: "샹떼자듀 합창단",
      orchestra: "샹떼자듀 챔버 오케스트라",
    },
    program: {
      part1: ["Ave Verum Corpus KV 618", "Exsultate, jubilate, KV 165"],
      part2: ["Mozart, Requiem In D minor KV 626"],
    },
    organizer: "사단법인 샹떼자듀합창단",
    sponsor: ["샹떼자듀 정기후원회", "라센느아트홀"],
    ticketing: ["티켓링크", "인터파크티켓"],
  },
  {
    id: 202304,
    title: "수난절 음악회 세자르 프랑크의 <십자가상의 칠언>",
    date: "2023년 4월 4일, 19:30",
    place: "영산아트홀",
    img_url: "/202304/01.jpg",
    performers: {
      conductor: "김혜옥",
      soloists: {
        소프라노: "최혜경",
        카운터테너: "장정권",
        테너: ["오의영", "고승우", "백인재"],
        베이스: "안대현",
      },
      choir: "샹떼자듀 합창단",
      orchestra: "바흐 솔리스텐 서울",
    },
    organizer: "사단법인 샹떼자듀합창단",
    sponsor: ["샹떼자듀 정기후원회", "라센느아트홀"],
    ticketing: ["인터파크티켓", "예스24"],
  },
  {
    id: 202203,
    title: "J.S.Bach의 '요한수난곡' Johannes-Passion BWV 245 전곡",
    date: "2022년 3월 24일, 19:30",
    place: "아트센터 인천 콘서트홀",
    img_url: "/202203/01.jpg",
    performers: {
      conductor: "김혜옥",
      soloists: {
        복음사가: "김세일",
        예수: "김현",
        소프라노: "윤지",
        카운터테너: "장정권",
        테너: "유종훈",
        베이스: "김우진",
      },
      choir: "샹떼자듀 합창단",
      orchestra: "알떼 무직 서울",
    },
    organizer: "사단법인 샹떼자듀합창단",
    sponsor: ["샹떼자듀 정기후원회", "라센느아트홀"],
    ticketing: ["인터파크티켓", "예스24"],
  },
  {
    id: 202209,
    title: "W. A. Mozrt의 레퀴엠 KV626",
    date: "2022년 9월 4일, 19:30",
    place: "아트센터 인천 콘서트홀",
    img_url: "/202209/01.jpg",
    performers: {
      conductor: "김혜옥",
      soloists: {
        소프라노: "최혜경",
        카운터테너: "장정권",
        테너: "김효종",
        베이스: "안대현",
      },
      choir: "샹떼자듀 합창단",
      orchestra: "샹떼 자듀 쳄버 오케스트라",
    },
    organizer: "사단법인 샹떼자듀합창단",
    sponsor: ["샹떼자듀 정기후원회", "라센느아트홀"],
    ticketing: ["인터파크티켓", "예스24"],
  },
  {
    id: 202212,
    title: "J.S.Bach의 '바흐 크리스마스 오라토리오",
    date: "2022년 12월 9일, 19:30",
    place: "영산 아트홀",
    img_url: "/202212/01.jpg",
    performers: {
      conductor: "김혜옥",
      soloists: {
        복음사가: "박승희",
        소프라노: "최혜경",
        카운터테너: "장정권",
        테너: "허남원",
        베이스: "윤종민",
      },
      choir: "샹떼자듀 합창단",
      orchestra: ["바흐 솔리스텐", "알떼 무직 서울"],
    },
    organizer: "사단법인 샹떼자듀합창단",
    sponsor: ["샹떼자듀 정기후원회", "라센느아트홀"],
    ticketing: ["인터파크티켓", "예스24"],
  },
  {
    id: 202104,
    title: "수난절 음악 예배",
    desc: "1년이면 코로나 스트레스가 가실까 했는데, 전염병의 위험은 여전히 우리주변을 긴장하게 합니다. 밝고 기분 좋은 뉴스는 보이지 않고, 어딜 가나 힘들다는 말만 들려 나옵니다. 옳고 당당한 것이 승리한다는 소식은 듣지 못하고, 자기가 옳다고 우기는 사람들의 이야기만 짜증스럽게 들어야 합니다. 차라리 세상과 떨어져서 지내고 싶고, 되도록 나만 쳐다보고 살고 싶다는 생각이 듭니다. '위드 코로나(with Covid19)' 시대에 많은 사람들이 겪게 되는 심리가 아닌가 합니다. 또한, 치료제 없는 전염병에 의해 누군가의 친구, 연인, 가족이 안타깝게 세상을 뜨는 것을 보면서 인생의 유한함에 대해서도 절감하게 됩니다.\n\n저는 이번 코로나로 인하여 소중한 친구 김인애 선생님을 하나님의 품으로 떠나 보내야만했습니다. 신앙의 동역자였던 친구는 성가대에서 하나님께 찬양 드리는 것을 유일한 기쁨으로 생각하며 소리 없이 성가대에 봉사하셨던 모습이 눈에 선합니다....(중략)",
    date: "2021년 4월 2일, 19:30",
    place: "광림아트센터 장천홀",
    img_url: "/202104/01.jpg",
    performers: {
      conductor: "김혜옥",
      soloists: {
        소프라노: "최혜경",
        테너: ["오의영", "백인재", "고승우"],
        베이스: "박주성",
      },
      choir: "샹떼 자 듀 합창단",
      orchestra: "바흐솔리스텐 서울",
    },
    program: {
      part1: [
        "O Vos Omnes(오 사람들이여) - Tomas Luis de Victoria(1548-1611)",
        "O Crux(오 십자가) - Knut Nystedt(1915-2014)",
        "Quatre Motets pour Temps de Penitence(4개의 수난절 모테트) - Francis Poulenc(1899-1963)",
        "Ah, Holy Jesus(아, 거룩하신 주님) - Setting John Ferguson(b.1941)",
      ],
      part2: [
        "Les Sept dernieres Paroles du Christ en Croix(십자가 상의 칠언) - Cesar Franck(1822-1890)",
        "prolog - O bos Omnes, qui transitis per viam",
        "1. Verbum - Pater, dimitte illis",
        "2. Verbum - Domine, memento mei, cum veneris in regnum tuum",
        "3. Verbum - Mulier, ecce filius tuus",
        "4. Verbum - Deus meus, ut quid dereliquisti me?",
        "5. Verbum - Sitio!",
        "6. Verbum - Consummatum est!",
        "7. Verbum - Pater, in manus tuas commendo spiritum meum",
      ],
    },
  },
  {
    id: 202012,
    title: "크리스마스 음악회",
    date: "2020년 12월 21일, 19:30",
    place: "광림아트센터 장천홀",
    img_url: "/202012/01.jpg",
    performers: {
      conductor: "김혜옥",
      soloists: {
        피아노: ["김혜련", "김채일"],
        오르간: "남에셀",
        카운터테너: "장정권",
        소프라노: "이지원",
        바리톤: "박주성",
        바이올린: "강유경",
        첼로: "송민제",
      },
    },
  }, // ... 이전 코드 계속

  {
    id: 201903,
    title: "정기연주회",
    date: "2019년 5월 16일, 19:30",
    place: "영산아트홀",
    img_url: "/201905/01.jpg",
    youtube_url: ["https://www.youtube.com/watch?v=zIWqR6YgUbk"],
    program: {
      part1: [
        "Psalm 96 - Jan Pieterszoon Sweelinck",
        "Exsultate Deo - Giovanni Pierluigi da Palestrina",
        "Usqeuquo Domine - Francisco Guerrero",
        "Abendlied - Josef Rheinberger",
        "Sanctus - Frank Martin",
        "Confitebor - Knut Nystedt",
        "Data est mihi omnis potestas - James MacMillan",
      ],
      part2: [
        "Lobet den Harren, alle Heiden BWV230 - Johann Sebastian Bach",
        "Jauchzet dem Herrn BWV Ahn.160 - Johann Sebastian Bach",
      ],
      part3: [
        "Violin Sonata No. 1 in A Minor, Op. 105중 - Robert Schmann",
        "Toccata und Fugge d-moll 中 Toccata, BWV565 - Johann Sebastian Bach",
      ],
      part4: [
        "Liebeslieser walzer Op.52 - Johannes Bhrams",
        "1. Rede, Mädchen, allzu liebes",
        "2. Am Gesteine rauscht die Flut",
        "3. O die Frauen",
        "4. Wie des Abends schöne Röte",
        "5. Die grüne Hopfenranke",
        "6. Ein keliner, hübscher Vogel",
        "11. Nein, es ist nicht auszukommen",
        "12. Schlosser auf, und mache Schlösser",
      ],
      part5: [
        "A tu lado - Javier Buso & Matias Anto Mens",
        "Marinero - Miguel Asins Arbo",
        "My Soul's Been Anchored in the Lord - Arr. Moses Hogan",
        "면류관 가지고 - George J. Elvey",
      ],
    },
    performers: {
      conductor: "김혜옥",
      viceconductor: "김태현",
    },
    organizer: "샹떼 자 듀 합창단",
    sponsor: ["연세대학교회", "은진교회"],
  },
  {
    id: 201912,
    title: "크리스마스 음악회",
    date: "2019년 12월 25일, 19:00",
    place: "연세대학교 루스채플",
    img_url: "/201912/01.jpg",
    performers: {
      conductor: "김혜옥",
      soloists: {
        소프라노: "최혜경",
        알토: "장정권",
        테너: "류성수",
        베이스: "박주성",
      },
      choir: "샹떼 자 듀 합창단",
      orchestra: "비흐솔리스텐서울",
    },
    organizer: "연세대학교회",
  },
  {
    id: 201803,
    title: "사순절연주회",
    desc: "교회음악의 거장 J.S.Bach 의 “요한수난곡 Johannes Passion, BWV 245 “ 는 수난곡으로 관중들을 그리스도의 수난의 현장에서 직접 관찰하고 체험케 하는 ‘음악 설교’ 입니다. 바흐는 단순한 관객에 머무르게 하지 않고, 그리스도의 수난에 직접 동참하게 하는 이들이 되게끔 하고 있습니다. 이 연주를 통해 십자가가 오늘을 살고 있는 우리에게 어떤 의미를 지니고 있는지, 우리는 자신에게 맡겨진 십자가를 어떻게 감당해야 하는지를 묵상하는 시간이 될 것입니다.",
    date: "2018년3월25일(일)19:00",
    place: "연세대학교 루스채플",
    img_url: "/201803/01.jpg",
    youtube_url: [
      "https://www.youtube.com/watch?v=RwdojTEkq-U",
      "https://www.youtube.com/watch?v=RibK8yred-w",
    ],
    performers: {
      conductor: "김혜옥",
      soloists: {
        예수: ["김현", "박주성"],
        빌라도: "박지민",
        소프라노: ["김호정", "차정은"],
        카운터테너: ["강예국", "김요섭"],
        오르간: "최호영",
        첼로: "강효정",
      },
      choir: "샹떼 자 듀 합창단",
      orchestra: "Alte Musik Seoul",
    },
    organizer: "사단법인 샹떼 자 듀 합창단",
    sponsor: "연세대학교회",
  },
  {
    id: 201805,
    title: "2018 정기연주회",
    desc: "2018년 제2회 정기연주회에서는 정기연주회에서는 르네상스 시대부터 바로크, 낭만, 현대 시대의 명곡들을 선곡하여 여러분을 만날 예정입니다. 1부에서는 독실한 카톨릭 신앙을 바탕으로한 F. Poulenc (1899~1963) 의G장조 미사(Mass in G major)를 2부에서는 J.S. Bach의 모테트 ‘주님께 감사의 새 노래를 불러드리자 (Singet dem Herrn ein neues Lied, BWV 225)’가 연주됩니다. 그 외 프로그램 모두 각기 개성있고 주옥같은 곡으로 다채로운 무대가 펼쳐집니다.",
    date: "2018년 5월 21일(월) 19:30",
    place: "영산아트홀",
    img_url: "/201805/01.jpg",
    performers: {
      conductor: "김혜옥",
      viceconductor: "김태현",
      choir: "샹떼 자 듀 합창단",
      piano: ["김혜련", "백은지"],
      orchestra: "Wiener Chamber",
    },
    organizer: "사단법인 샹떼 자 듀 합창단",
    sponsor: ["연세대학교회", "은진교회", "DC Advertising"],
  },
  {
    id: 201812,
    title: "크리스마스 음악회",
    desc: "우리를 구원하시기 위해 추운 겨울 이 땅의 소망이 되어 오신 메시아 예수 그리스도, 그 분과의 만남을 위해 오늘 이 자리에 모인 여러분들을 진심으로 환영합니다. 음악은 사람의 지성과 감성을 일깨우는 종합 예술입니다. 음악은 새로운 생각을 갈구하는 사람에게 통찰을 제공하고, 상처받은 사람의 가슴을 어루만지고 위로해 줍니다. 또 음악은 그 시대의 의미를 음미하기 위한 질문을 던지고 대답하는 역할을 하기도 합니다. 1897년 오스트리아의 빈에 모인 예술가들이 `그 시대에는 그 나름의 예술을, 그리고 그 예술에는 자유를`이라는 비전을 선언했던 사건도 같은 이유에서 출발한 것이라고 봅니다...(중략)",
    date: "2018년 12월 19일, 19:30",
    place: "연세대학교 루스채플",
    img_url: "/201812/01.jpg",
    performers: {
      conductor: "김혜옥",
      soloists: {
        소프라노: ["이은혜", "민한별"],
        알토: "권용범",
        테너: "유종훈",
        베이스: ["김현", "박주성"],
      },
      choir: "샹떼 자 듀 합창단",
      orchestra: "알테뮤지크서울",
    },
    organizer: "연세대학교회",
  },
  {
    id: 201704,
    title: "바흐 – 요한수난곡 사순절 음악회",
    desc: "연세대학교회의 “일요음악회 시리즈”를 통해 음악설교자J.S Bach 의 Johanness Passion, BWV 245 를 사순절 음악회로 올립니다. 바흐는 예수 그리스도의 수난이라는 역사적 사실을 음악으로 입증하기 위해 ‘오라토리오 수난곡’ 형태로 복음의 대서사시를 썼습니다. 이 수난곡을 통해서 “나는 정말로 예수처럼 살 준비가 되어 있는가” 라는 어마어마한 질문을 던지게 될것입니다.",
    date: "2017년4월9일(일)19:00",
    place: "연세대학교 루스채플",
    img_url: "/201704/01.jpg",
    performers: {
      conductor: "김혜옥",
      soloists: {
        복음사가: "권지호",
        예수: "박주성",
        빌라도: "박지민",
        소프라노: ["한송이", "차정은"],
        알토: ["김요섭", "마재원"],
        테너: "오의영",
      },
      choir: "샹떼 자 듀 합창단",
      orchestra: "Orchestre de Chambre du Chantez à Dieu Alte Musik Seoul",
    },
    organizer: "연세대학교회",
    sponsor: "연세대학교회",
  },
  {
    id: 201708,
    title: "제50회 획기적 합창세미나, 김헤옥 지휘자 지휘 분반실습 시범합창단",
    desc: "English Anthem and Spiritual, 영국성가곡과 흑인영가 한국교회음악협회의 획기적합창세미나는 교회음악사역에 새로운 변화를 주도해 오고 있습니다. 샹떼 자 듀는 김혜옥 음악감독의 분반실습 세미나에 중 모범합창단의 역할로 함께 합니다.",
    date: "2017년 8월 1일~3일, 09:00-10:00",
    place: "사랑의교회(서초)",
    img_url: "/201708/01.jpg",
    performers: {
      conductor: "김혜옥",
      choir: "샹떼 자 듀 합창단",
      piano: "김혜련",
    },
    organizer: ["한국교회음악협회", "사랑의교회 찬양분과"],
  },
  {
    id: 201709,
    title: "20th춘천국제 고음악제 폐막공연",
    desc: "샹떼 자 듀 합창단의 지휘자 김혜옥 교수는 젊은 합창단원과 솔리스트들을 키워내며 르네상스, 바로크, 고전, 낭만 시대의 작품들을 연구하고, 특히 바하의 칸타타, 모테트, 수난곡들을 주로 연주하여 깊이를 더 해 가고 있습니다. 이번 연주회에서는 바하 모테트 BWV226과 우리에게 친숙한 칸타타 BWV147, Herz und Mund und Tat und Leben을 선사합니다.",
    date: "2017년9월29일(금)19:00",
    place: "죽림동 주교좌 성당",
    img_url: "/201709/01.jpg",
    performers: {
      conductor: "김혜옥",
      choir: "샹떼 자 듀 합창단",
      orchestra: "페스티발 앙상블",
    },
    organizer: ["춘천시", "(사)춘천국제고음악제"],
    sponsor: "(사) 춘천국제고음악제",
  },
  {
    id: 201710,
    title: "2017 한국합창대제전",
    date: "2017년10월23일~25일 저녁8시",
    place: "롯데콘서트홀",
    img_url: "/201710/01.jpg",
  },
  {
    id: 2017121,
    title: "2017 산울교회 창립20주년 기념 음악회 초청연주",
    desc: "산울교회 창립 20주년을 기념하고 군포지역의 이웃들과 사랑을 나누는 자리, “샹떼 자 듀 초청 음악회”를 올립니다.",
    date: "2017년 12월 2일 (주일) 19:00",
    place: "산울교회 본당(4층)",
    img_url: "/201712_1/01.png",
    performers: {
      conductor: "김혜옥",
      viceconductor: "김태현",
      choir: "샹떼 자 듀 합창단",
      orchestra: "페스티발 앙상블",
    },
    program: {
      part1: [
        'PSALM 96 "시편 96편" – J. P. Sweelink',
        'Jubilate Deo "여호와를 즐거이 부를 지어다" – Fredrik Sixten',
        'Even when he is silent "주가 잠잠하실 지라도" – Kim André Arnes',
        'Witness "증인" – Arr. Jack Halloran',
      ],
      part2: [
        'Herz und Mund Tat und Leben, BWV147 "마음과 입과 행함과 삶이" – J. S. Bach',
      ],
    },
    organizer: "군포 산울",
  },
  {
    id: 201712,
    title: "2017 바흐 – 크리스마스 오라토리오 크리스마스 이브 음악회",
    desc: "크리스마스 이브, 교회음악의 정수 J. S. Bach의 대작 Christmas Oratoria로 이 땅에 오신 사랑, 예수 그리스도를 노래합니다. 이번 연주는 음악감독 김혜옥 교수의 지휘 아래 세계적인 하프시코디스트 조성연 교수가 함께 하며 유럽 무대를 중심으로 활발한 활동중인 세계적인 카운터테너 장정권과 소프라노 최혜경 그리고 지난 요한수난곡으로 무대를 올린 테너 권지호, 베이스 박주성, 소프라노 마재원이 협연에 나섭니다. 아울러 고음악 전문 연주단체인 Alte Musik Seoul과 한국 예배음악을 선두해가는 연세대학교회 성가대와 함께 하는 이번 연주에서는 A. Adams의 O Holy Night외 다수의 성탄 캐롤이 연주되어질 예정입니다. 추운 겨울, 따뜻한 사랑으로 오신 예수 그리스도를 찬양하는 자리에 함께 해주시기를 바랍니다",
    date: "2017년12월24일(일)19:00",
    place: "연세대학교 루스채플",
    img_url: "/201712_2/01.jpg",
    youtube_url: [
      "https://www.youtube.com/watch?v=oXcKwYqaFfA",
      "https://www.youtube.com/watch?v=E3BUYOKOlC4",
    ],
    performers: {
      conductor: "김혜옥",
      viceconductor: "권수정",
      soloists: {
        소프라노: ["마재원", "최혜경"],
        알토: "장정권",
        테너: "권지호",
        베이스: "박주성",
        첼로: "강효정",
        쳄발로: "조성연",
      },
      choir: ["샹떼 자 듀 합창단", "연세대학교회 성가대"],
      orchestra: "Alte Musik Seoul",
    },
    organizer: ["사단법인 샹떼 자 듀 합창단", "연세대학교회"],
  },
];

export async function getConcert(id: string): Promise<IConcert> {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_API_URL}/api/concerts/${id}`,
    { cache: "no-store" }
  );
  if (!res.ok) {
    throw new Error("Failed to fetch concert data");
  }
  return res.json();
}
